config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "ea2.be"
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#impressions"
  get "before_and_after", to: "pages#before_and_after"
  get "at_work", to: "pages#at_work"
  get "about", to: "pages#about"
  get "antiques", to: "pages#antiques"
  get "arts", to: "pages#arts"
  get "flooring", to: "pages#flooring"
  resource :articles, only: [:new, :create, :edit, :update, :destroy, :show]
  resource :messages, only: [:create]
  get "admin", to: "articles#index"
  get "toggle_arts", to: "settings#toggle_arts", as: "toggle_arts"
  get "toggle_antiques", to: "settings#toggle_antiques", as: "toggle_antiques"
  get "toggle_flooring", to: "settings#toggle_flooring", as: "toggle_flooring"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_many_attached :photos
  has_many :messages, dependent: :destroy

  CATEGORIES = %w[
    Antiques
    Arts
    Flooring
  ].freeze

  scope :antiques, -> { where(category: "Antiques").order(:created_at) }
  scope :arts, -> { where(category: "Arts").order(:created_at) }
  scope :flooring, -> { where(category: "Flooring").order(:created_at) }

  before_destroy :delete_photos

  private

  def delete_photos
    photos.each do |photo|
      Cloudinary::Uploader.destroy(photo.key)
      photo.purge
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :article

  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true
  validates :article, presence: true

  after_save :send_to_each_user

  private

  def send_to_each_user
    User.all.each do |user|
      Pony.mail(
        to: user.email,
        via: :smtp,
        subject: "New contact message for EA2",
        body: create_body,
        via_options: {
          address: "smtp.gmail.com",
          port: 587,
          enable_starttls_auto: true,
          user_name: ENV["GMAIL_EMAIL"],
          password: ENV["GMAIL_PASSWORD"],
          authentication: :login
        }
      )
    end
  end

  def create_body
    "DON'T REPLY TO THIS EMAIL ADDRESS \n--------------\n\nThere is a new contact form created!\nArticle: #{article.title}\n\nName: #{name}\nEmail: #{email}\n\nMessage: #{content}"
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sing_in_path_for(resource)
    articles_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    skip_before_action :authenticate_user!, only: :show

  def index
    @articles = Article.all.order(:id)
  end

  def show
    @article = Article.find(params[:id])
    @new_message = @article.messages.build
  end

  def new
    @new_article = Article.new
  end

  def create
    article = Article.new(article_params)
    if article.save
      redirect_to admin_path, notice: "Article succesfully created"
    else
      render :new, alert: article.errors.full_messages.join(', ')
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    if article.update(article_params)
      redirect_to admin_path, notice: "Article succesfully created"
    else
      render :edit, alert: article.errors.full_messages.join(', ')
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      redirect_to admin_path
    else
      render :index, alert: @article.errors.full_messages.join(', ')
    end
  end

  private

  def article_params
    params.require(:article).permit(
      :title,
      :description,
      :price,
      :category,
      :dimensions,
      photos: []
    )
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    skip_before_action :authenticate_user!

  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to articles_path(id: message_params[:article_id]), notice: "Message successfully sent!" }
      else
        format.html { redirect_to articles_path(id: message_params[:article_id]), alert: "We're sorry, something went wrong!" }
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(
      :name,
      :email,
      :content,
      :article_id
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def impressions
  end

  def before_and_after
  end

  def at_work
  end

  def about
  end

  def antiques
    # Render another page if settings say we don't display this yet!!
    render("impressions") unless Setting.first.display_antiques
    @articles = Article.antiques
  end

  def arts
    # Render another page if settings say we don't display this yet!!
    render("impressions") unless Setting.first.display_arts
    @articles = Article.arts
  end

  def flooring
    # Render another page if settings say we don't display this yet!!
    render("impressions") unless Setting.first.display_flooring
    @articles = Article.flooring
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def toggle_arts
    setting = Setting.first
    setting.display_arts = !setting.display_arts
    if setting.save
      redirect_to admin_path, notice: "Arts are now being #{setting.display_arts ? "displayed" : "hidden"}"
    else
      redirect_to admin_path, alert: setting.errors.full_messages.join(", ")
    end
  end

  def toggle_antiques
    setting = Setting.first
    setting.display_antiques = !setting.display_antiques
    if setting.save
      redirect_to admin_path, notice: "Antiques are now being #{setting.display_antiques ? "displayed" : "hidden"}"
    else
      redirect_to admin_path, alert: setting.errors.full_messages.join(", ")
    end
  end

  def toggle_flooring
    setting = Setting.first
    setting.display_flooring = !setting.display_flooring
    if setting.save
      redirect_to admin_path, notice: "Floorings are now being #{setting.display_flooring ? "displayed" : "hidden"}"
    else
      redirect_to admin_path, alert: setting.errors.full_messages.join(", ")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/articles/edit.html.erb
<h2>Edit Article</h2>
<%= form_for @article, url: articles_path(id: @article.id), html: { class: "new-article-form" } do |f| %>
  <%= f.label "Title", class: "form-label" %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label "Category", class: "form-label", for: "category-new-article" %>
  <%= f.select :category, Article::CATEGORIES, {}, { class: "form-control", id: "category-new-article" } %>
  <%= f.label "Description", class: "form-label" %>
  <%= f.text_area :description, class: "form-control" %>
  <%= f.label "Dimensions", class: "form-label" %>
  <%= f.text_field :dimensions, class: "form-control" %>
  <%= f.label "Price", class: "form-label" %>
  <%= f.number_field :price, step: 0.01,class: "form-control" %>
  <%= f.label "Upload Photo", class: "form-label" %><br>
  <%= f.file_field :photos, multiple: true %><br>
  <% @article.photos.each do |image| %>
    <%= image_tag(image.url, class: "admin-article-image") %><br>
  <% end %>
  <%= f.submit "Edit", class: "btn btn-primary" %>
<% end %>
<%= link_to "Go Back", admin_path, class: "btn btn-secondary" %>

app/views/articles/index.html.erb
<%# iterate through all the articles, display mini cards of them %>
<%= link_to "Add Article", new_articles_path, class: "btn btn-primary" %>
<%= link_to "Toggle Arts", toggle_arts_path, class: "btn btn-warning" %>
<%= link_to "Toggle Antiques", toggle_antiques_path, class: "btn btn-warning" %>
<%= link_to "Toggle Flooring", toggle_flooring_path, class: "btn btn-warning" %>
<%= link_to "Invite User", new_user_invitation_path, class: "btn btn-info" %>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @articles.each do |article| %>
    <div class="col">
      <div class="card" style="width: 18rem; margin: 1rem 1rem;">
        <img src="<%= article.photos.first.url %>" class="card-img-top" style="height: 300px; object-fit: cover">
      <div class="card-body">
        <h5 class="card-title"><%= article.title %></h5>
        <p class="card-text"><%= article.category %></p>
        <%= link_to "Edit", edit_articles_path(id: article.id), class: "btn btn-secondary" %>
        <%= link_to "Destroy", articles_path(id: article.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/invite_new_user.html.erb
<h2>New User</h2>
<%= form_for @new_user, url: invite_user_path(@new_user), html: { class: "new-article-form" } do |f| %>
  <%= f.label "Email", class: "form-label" %>
  <%= f.text_field :email, class: "form-control" %>
  <%= f.submit "Invite", class: "btn btn-primary" %>
<% end %>
<%= link_to "Go Back", admin_path, class: "btn btn-secondary" %>

app/views/articles/new.html.erb
<h2>New Article</h2>
<%= form_for @new_article, url: articles_path(@new_article), html: { class: "new-article-form" } do |f| %>
  <%= f.label "Title", class: "form-label" %>
  <%= f.text_field :title, class: "form-control", required: true %>
  <%= f.label "Category", class: "form-label", for: "category-new-article" %>
  <%= f.select :category, Article::CATEGORIES, { include_blank: '-- Select One --' }, { class: "form-control", id: "category-new-article", required: true } %>
  <%= f.label "Description", class: "form-label" %>
  <%= f.text_area :description, class: "form-control", required: true %>
  <%= f.label "Dimensions", class: "form-label" %>
  <%= f.text_field :dimensions, class: "form-control" %>
  <%= f.label "Price (optional)", class: "form-label" %>
  <%= f.number_field :price, step: 0.01, class: "form-control" %>
  <%= f.label "Upload Photo (first one selected will be the thumbnail)", class: "form-label" %><br>
  <%= f.file_field :photos, multiple: true, required: true %><br>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>
<%= link_to "Go Back", admin_path, class: "btn btn-secondary" %>

app/views/articles/show.html.erb
<div class="article-big-wrapper">
  <div class="article-box carousel slide" id="articles-carousel" data-interval="false" data-touch="true" data-ride="carousel">
    <div class="article-box-top-arrow mobile-hide">
      <% if @article.category == "Antiques" %>
        <%= link_to antiques_path do %>
          <div class="arrow-hover-wrapper">
            <%= inline_svg_tag "polygon-back-arrow.svg", class: "article-back-arrow" %>
            <p class="back-arrow-text">BACK</p>
          </div>
        <% end %>
      <% elsif @article.category == "Arts" %>
        <%= link_to arts_path do %>
          <div class="arrow-hover-wrapper">
            <%= inline_svg_tag "polygon-back-arrow.svg", class: "article-back-arrow" %>
            <p class="back-arrow-text">BACK</p>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="article-box-top-left mobile-hide"></div>
    <div class="article-box-top-middle">
      <p class="article-box-text"><%= @article.title %></p>
    </div>
    <div class="article-box-top-right mobile-hide"></div>
    <div class="article-box-middle-left mobile-hide" href="#articles-carousel" role="button" data-slide="prev">
      <%= inline_svg_tag "polygon-back-arrow.svg", class: "article-arrow-left" %>
    </div>
    <div class="article-box-middle-middle">
      <div class="carousel-inner" align="center">
        <% @article.photos.each_with_index do |photo, i| %>
          <div class="carousel-item<%= i.zero? ? " active" : "" %>">
            <img src="<%= photo.url %>">
          </div>
        <% end %>
      </div>
    </div>
    <a class="article-box-middle-right mobile-hide" href="#articles-carousel" role="button" data-slide="next">
      <%= inline_svg_tag "polygon-back-arrow.svg", class: "article-arrow-right" %>
    </a>
    <div class="article-box-bottom-left mobile-hide"></div>
    <div class="article-box-bottom-double-left mobile-hide"></div>
    <div class="article-box-bottom-middle">
      <p id="article-box-dimensions" class="article-box-text"><%= @article.dimensions %></p>
    </div>
    <div class="article-box-bottom-right mobile-hide"></div>
  </div>
  <div class="article-second-box mobile-hide">
    <div class="article-second-box-top-left"></div>
    <div class="article-second-box-top-middle"></div>
    <div class="article-second-box-top-right"></div>
    <div class="article-second-box-middle-left"></div>
    <div class="article-second-box-middle-middle">
      <button type="button" class="article-contact-us-btn" data-toggle="modal" data-target="#contactModal">
        Contact Us
      </button>
    </div>
    <div class="article-second-box-middle-right"></div>
    <div class="article-second-box-bottom-left"></div>
    <div class="article-second-box-bottom-middle">
      <p class="article-description"><%= @article.description %></p>
    </div>
    <div class="article-second-box-bottom-right"></div>
  </div>

  <div class="article-second-box-flex hide-non-mobile">
    <p class=""><%= @article.description %></p>
    <button type="button" class="" data-toggle="modal" data-target="#contactModal">
      Contact Us
    </button>
  </div>
</div>

<%# contact us modal %>
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contact-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title weight-300" id="contact-modal-label">Contact Us</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body weight-300">
        <%= form_for @new_message, url: messages_path, html: { class: "new-article-form" } do |f| %>
          <%= f.label "Name", class: "form-label" %>
          <%= f.text_field :name, class: "form-control", required: true %>
          <%= f.label "Email", class: "form-label" %>
          <%= f.text_field :email, class: "form-control", required: true %>
          <%= f.label "Message", class: "form-label" %>
          <%= f.text_area :content, class: "form-control", required: true %>
          <%= f.hidden_field :article_id, value: @article.id %>
      </div>
      <div class="modal-footer">
        <%= f.submit "Send", class: "btn btn-primary contact-send-btn" %>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <!-- viewport meta to reset iPhone inital scale -->
    <%# <link rel="stylesheet" href="menu/responsivemobilemenu.css" type="text/css"/> %>
    <%# <script type="text/javascript" src="jquery.min.js"></script> %>
    <%# <script type="text/javascript" src="menu/responsivemobilemenu.js"></script> %>
    <%# <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"> %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="RomanVanLoo">
    <meta name="keywords" content="EA2, experts in antique, stone &amp; wood"/>
    <meta name="description" content="EA2, experts in antique, stone and wood"/>
    <title><%= content_for?(:html_title) ? yield(:html_title) : "EXPERTS IN ANTIQUE - STONE & WOOD - EA2" %></title>
    <%# <link rel="stylesheet" href="css/stylesheet.css" type="text/css"/> %>
    <%# down here comes from rails %>

    <%= favicon_link_tag asset_path('favicon.ico') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
  </head>

  <body>
    <div id="notice-alert">
      <%= render 'shared/notice' %>
    </div>

    <div id="pagewrap">
      <div id="header">
        <div id="logo">
          <%= link_to root_path do %>
            <%= image_tag ("logo-344x65.png"), class: "ri", style: "margin-top: 5px" %>
          <% end %>
        </div>
        <div class="rmm">
          <ul>
            <% if Setting.first.display_antiques %>
              <li><%= link_to "Antiques", antiques_path, class: "#{"active" if (current_page?(antiques_path) || @article&.category == 'Antiques')}" %></li>
            <% end %>

            <% if Setting.first.display_arts %>
              <li><%= link_to "Arts", arts_path, class: "#{"active" if (current_page?(arts_path) || @article&.category == 'Arts')}" %></li> 
            <% end %>

            <% if Setting.first.display_flooring %>
              <li><%= link_to "Flooring", flooring_path, class: "#{"active" if (current_page?(flooring_path) || @article&.category == 'Flooring')}" %></li> 
            <% end %>
            <li><%= link_to "Impressions", root_path, class: "#{"active" if current_page?(root_path)}" %></li>
            <li><%= link_to "Before & After", before_and_after_path, class: "#{"active" if current_page?(before_and_after_path)}" %></li>
            <li><%= link_to "At Work", at_work_path, class: "#{"active" if current_page?(at_work_path)}" %></li>
            <li><%= link_to "About", about_path, class: "#{"active" if current_page?(about_path)}" %></li>
            <% unless current_user.blank? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign_out_btn" %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <%= yield %>
    </div>

    <%# SET NAVBAR %>
    <script>
      function responsiveMobileMenu() {
        $('.rmm').each(function() {
          $(this).children('ul').addClass('rmm-main-list');	// mark main menu list
          var $style = $(this).attr('data-menu-style');	// get menu style
          if ( typeof $style == 'undefined' ||  $style == false )
          {
            $(this).addClass('graphite'); // set graphite style if style is not defined
          }
          else {
            $(this).addClass($style);
          }
        });
      }

function getMobileMenu() {
  /* 	build toggled dropdown menu list */
    $('.rmm').each(function() {
      var menutitle = $(this).attr("data-menu-title");
      if ( menutitle == "" ) {
        menutitle = "Menu";
      }
      else if ( menutitle == undefined ) {
        menutitle = "Menu";
      }
      var $menulist = $(this).children('.rmm-main-list').html();
      var $menucontrols ="<div class='rmm-toggled-controls'><div class='rmm-toggled-title'>" + menutitle + "</div><div class='rmm-button'><span>&nbsp;</span><span>&nbsp;</span><span>&nbsp;</span></div></div>";
      $(this).prepend("<div class='rmm-toggled rmm-closed'>"+$menucontrols+"<ul>"+$menulist+"</ul></div>");

    });
}

function adaptMenu() {

  /* 	toggle menu on resize */

    $('.rmm').each(function() {
      var $width = $(this).css('max-width');
      $width = $width.replace('px', '');
      if ( $(this).parent().width() < $width*1.05 ) {
        $(this).children('.rmm-main-list').hide(0);
        $(this).children('.rmm-toggled').show(0);
      }
      else {
        $(this).children('.rmm-main-list').show(0);
        $(this).children('.rmm-toggled').hide(0);
      }
    });

}

$(function() {
  responsiveMobileMenu();
  getMobileMenu();
  adaptMenu();
  /* slide down mobile menu on click */
    $('.rmm-toggled, .rmm-toggled .rmm-button').click(function(){
      if ( $(this).is(".rmm-closed")) {
        $(this).find('ul').stop().show(300);
        $(this).removeClass("rmm-closed");
      }
      else {
        $(this).find('ul').stop().hide(300);
        $(this).addClass("rmm-closed");
      }
    });
});

/* 	hide mobile menu on resize */
  $(window).resize(function() {
    adaptMenu();
  });
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for(:html_title) { 'ABOUT - EA2' } %>
<div id="content">
  <div id="spacing" style="margin: 0px 30px;">
    <p>EA2 is an international boutique firm known for our supply of and design with exclusive and original antique building materials used in high-profile residential projects.</p>
    <p>We specialize in Blue Heaven<sup>®</sup> Historical Stone, stone that is reclaimed and is known as being the Rolls Royce of stone floors.</p>
    <p>We are part of the process from the drawings by the designers all the way through to the installation.</p>
    <p>Our customers — homeowners, architects, and interior designers — seek out our innovative ideas in order to find and design with the highest quality materials to use in their projects.</p>
    <p>Our objective is to always provide the feeling that the materials are a part of the original structure or scene.</p>
    <p>Another aspect of our business that we take pride in is the close relationship we develop with our clients and the bond that is formed between clients and materials. A true friendship is formed in the process, as our clients join us to see the materials as they once were, and imagined as what they could be.</p>
    <p>Our clients especially embrace the design process by coming to Europe to gain a first hand experience of procuring materials. Clients become more connected to their home by expressing their unique tastes through choices they make. These choices will complement the overall aesthetic as well as the creative design work that goes on behind the scenes for them.</p>
    <p>The following original and exclusive materials with unique patinas can be provided to your Architectural and Landscape projects: </p>
    <ul>
      <li><strong>Blue Heaven<sup>®</sup> Historical Stone</strong> | 18th C &gt; 20th C<br/>Floors, Staircases, Garden Steps and Pool Copings</li>
      <li><strong>Antique White Marble</strong> | 18th C &gt; 20th C <br/>Floors and Staircase</li>
      <li><strong>Antique French Oak</strong> | 18th C &gt; 20th C <br/>Floors, Parquets and Staircases</li>
      <li><strong>Antique French Oak</strong> | 19th C &gt; 20th C <br/>Beams and Ceilings</li>
      <li><strong>Antique Cobblestones</strong> | 17th C &gt; 20th C <br/>Unique colors and Sizes</li>
      <li><strong>Antique Oak and Pine</strong> | 18th C &gt; 20th C <br/>Doors</li>
      <li><strong>Historical Bricks</strong> | 18th C &gt; 20th C <br/>Unique Colors and Sizes</li>
      <li><strong>Antique Limestone</strong> | 18th C &gt; 20th C <br/>Floors, Fireplaces, Fountains and Garden Artifact</li>
      <li><strong>Antique Marbles</strong> | 18th C &gt; 20th C <br/>Floors, Fireplaces, Fountains and Garden Artifactse</li>
      <li><strong>Scura<sup>®</sup> Finishes</strong> | 18th C &gt; 20th C<br/>Lime finishes on walls, floors and bathrooms based on 18th C lime-techniques</li>
    </ul>
    <p>After all the packing and shipping is arranged we also enjoy being part of the installation process, as we work first hand with unique design groups, contractors and installers to oversee the installation of these wonderful materials and ensure that their true beauty is brought out through proper installation and finishes.</p>
    <p>Our firm's commissions include work from such notable clients as Tom Brady, Giselle Bundchen, Reed and Delphine Krakoff, John and Maureen Hailer, Michael and Lisa Bronner.</p>
    <p>Thank you for your interest in our firm. We look forward to meeting you and helping you to create the most beautiful and original home possible.</p>
    <div style="display: flex; justify-content: center;">
      <img src="https://res.cloudinary.com/ddngbvo3j/image/upload/v1612629186/ea2_V2/about/architectural-digest.jpg"/>
    </div>
    <p>We wish you a beautiful rest of the day,</p>
    <p>
    with Kindest Regards,<br/>
    Koen Van Loo<br/>
    owner and founder <br/>
    EA2   experts in antique stone and wood
    </p>
    <p>
    <strong>Address</strong><br/>
    BELGIUM <img src="https://res.cloudinary.com/ddngbvo3j/image/upload/v1612696968/ea2_V2/about/square.png" width="6" style="vertical-align:middle; margin-left: 5px; margin-right:5px;"/> Itegembaan 4a <img src="https://res.cloudinary.com/ddngbvo3j/image/upload/v1612696968/ea2_V2/about/square.png" width="6" style="vertical-align:middle; margin-left: 5px; margin-right:5px;"/> 2580 Putte
    </p>
    <p>
    <strong>Showroom</strong><br/>
    USA <img src="https://res.cloudinary.com/ddngbvo3j/image/upload/v1612696968/ea2_V2/about/square.png" width="6" style="vertical-align:middle; margin-left: 5px; margin-right:5px;"/> 741 Main Road <img src="https://res.cloudinary.com/ddngbvo3j/image/upload/v1612696968/ea2_V2/about/square.png" width="6" style="vertical-align:middle; margin-left: 5px; margin-right:5px;"/> 02646 Harwichport MA
    </p>
    <p>
    <strong>Contact</strong><br/>
    USA-Showroom +1 617 991 07 15<br/>
    BELGIUM +32 477 56 03 38<br/>
    <a href="mailto: ea2@me.com" target="_blank">ea2@me.com</a> <img src="https://res.cloudinary.com/ddngbvo3j/image/upload/v1612696968/ea2_V2/about/square.png" width="6" style="vertical-align:middle; margin-left: 5px; margin-right:5px;"/> <a href="/">ea2.be</a>
    </p>
    <p>&nbsp;</p>
  </div>
</div>
<div style="clear:both;"></div>	<div id="footer">
</div>

app/views/pages/antiques.html.erb
<% content_for(:html_title) { 'ANTIQUES - EA2' } %>

<div id="content">
  <div class="article-container">
    <% @articles.each do |article| %>
      <%= link_to articles_path(id: article.id) do %>
        <div class="article-card">
          <img src="<%= article.photos.first.url %>" class="card-img-top" style="object-fit: cover">
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/arts.html.erb
<% content_for(:html_title) { 'ARTS - EA2' } %>

<div id="content">
  <div class="article-container">
    <% @articles.each do |article| %>
      <%= link_to articles_path(id: article.id) do %>
        <div class="article-card">
          <img src="<%= article.photos.first.url %>" class="card-img-top" style="object-fit: cover">
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/settings/update.html.erb
<h1>Settings#update</h1>
<p>Find me in app/views/settings/update.html.erb</p>